app = "con9sole-bartender"
primary_region = "hkg"

[processes]
app = "python main.py"

[vm]
cpu_kind = "shared"
cpus = 1
memory_mb = 256

[experimental]
auto_rollback = true
auto_stop_machines = false   # Bot 長駐
auto_start_machines = true   # 有請求會自動啟動
