from __future__ import annotations

import time
from collections.abc import Callable

import discord

import config
from core.safe_send import send_or_followup
from features.menu_stats import record_usage_sync

INVITE_CHANNEL_ID = getattr(config, "INVITE_CHANNEL_ID", None)
INVITE_MAX_AGE_SECONDS = 7 * 24 * 60 * 60
INVITE_MAX_USES = 10
INVITE_COOLDOWN_SECONDS = 10 * 60
USER_INVITE_COOLDOWNS: dict[int, float] = {}


def get_invite_retry_after(user_id: int) -> float:
    last_used = USER_INVITE_COOLDOWNS.get(user_id, 0.0)
    elapsed = time.time() - last_used
    retry_after = INVITE_COOLDOWN_SECONDS - elapsed
    return retry_after if retry_after > 0 else 0.0


def touch_invite_cooldown(user_id: int) -> None:
    USER_INVITE_COOLDOWNS[user_id] = time.time()


def format_retry_seconds(seconds: float) -> str:
    seconds_int = max(0, int(seconds + 0.999))
    minutes, sec = divmod(seconds_int, 60)
    if minutes <= 0:
        return f"{sec} 秒"
    return f"{minutes} 分 {sec} 秒"


async def safe_defer(interaction: discord.Interaction, *, ephemeral: bool = True) -> None:
    if interaction.response.is_done():
        return
    try:
        await interaction.response.defer(ephemeral=ephemeral, thinking=True)
    except discord.HTTPException:
        pass


async def create_invite_link_from_button(
    interaction: discord.Interaction,
    *,
    can_use_admin_func: Callable[[discord.Member | discord.User], bool],
) -> None:
    await safe_defer(interaction, ephemeral=True)

    if not can_use_admin_func(interaction.user):
        retry_after = get_invite_retry_after(interaction.user.id)
        if retry_after > 0:
            await send_or_followup(
                interaction,
                content=f"⏳ 你啱啱已經產生過邀請碼，請等 {format_retry_seconds(retry_after)} 後再試。",
                ephemeral=True,
            )
            return

    record_usage_sync("invite", interaction.user.id, interaction.guild_id)

    if INVITE_CHANNEL_ID is None:
        await send_or_followup(
            interaction,
            content=(
                "⚠️ 未設定邀請入口頻道。\n"
                "請先喺 `config.py` 加：\n"
                "`INVITE_CHANNEL_ID: int = 你的channel_id`"
            ),
            ephemeral=True,
        )
        return

    channel = interaction.client.get_channel(int(INVITE_CHANNEL_ID))
    if channel is None:
        try:
            channel = await interaction.client.fetch_channel(int(INVITE_CHANNEL_ID))
        except discord.HTTPException:
            channel = None

    if not isinstance(channel, (discord.TextChannel, discord.VoiceChannel, discord.StageChannel)):
        await send_or_followup(
            interaction,
            content="⚠️ 搵唔到指定邀請入口頻道，請檢查 `INVITE_CHANNEL_ID`。",
            ephemeral=True,
        )
        return

    try:
        invite = await channel.create_invite(
            max_age=INVITE_MAX_AGE_SECONDS,
            max_uses=INVITE_MAX_USES,
            unique=True,
            temporary=False,
            reason=f"Invite generated by {interaction.user} ({interaction.user.id}) via Bartender menu",
        )
    except discord.Forbidden:
        await send_or_followup(
            interaction,
            content=f"❌ Bartender 無權喺 {channel.mention} 建立 invite，請開啟 `Create Instant Invite` 權限。",
            ephemeral=True,
        )
        return
    except discord.HTTPException as exc:
        await send_or_followup(
            interaction,
            content=f"❌ 建立邀請碼失敗：{type(exc).__name__}",
            ephemeral=True,
        )
        return

    if not can_use_admin_func(interaction.user):
        touch_invite_cooldown(interaction.user.id)

    public_message = (
        "🔗 **邀請碼已生成：**\n"
        f"{invite.url}\n\n"
        "有效期：`7 日`\n"
        "使用次數：`最多 10 次`\n"
        "成員類型：`非 temporary member`\n\n"
        "大家可以 copy 呢條 link share 畀朋友加入社群。"
    )

    try:
        if interaction.channel is None:
            raise RuntimeError("No interaction channel")
        await interaction.channel.send(public_message)
    except Exception as exc:
        await send_or_followup(
            interaction,
            content=f"❌ 邀請碼已建立，但公開發送失敗：{type(exc).__name__}\n{invite.url}",
            ephemeral=True,
        )
        return

    await send_or_followup(interaction, content="✅ 邀請碼已公開發送到此頻道。", ephemeral=True)
