# cogs/cheers.py (Embed + 30s cooldown, fix mention clickable, 打氣放最前)
from __future__ import annotations
import random
import discord
from discord import app_commands, Embed
from discord.ext import commands
import config


CHEERS_QUOTES: list[tuple[str, str, str]] = [
    ("Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and most of all, love of what you are doing.", "成功不是偶然的。它是努力、堅持、學習、犧牲，更重要的是你對正在做的事的熱愛。", "Pelé"),
    ("The more difficult the victory, the greater the happiness in winning.", "勝利越艱難，贏得時的喜悅就越大。", "Pelé"),
    ("Talent wins games, but teamwork and intelligence win championships.", "天賦能贏比賽，但團隊合作與智慧才能贏得冠軍。", "Michael Jordan"),
    ("I've failed over and over and over again in my life and that is why I succeed.", "我一生中一次又一次失敗，因此我才成功。", "Michael Jordan"),
    ("Obstacles don’t have to stop you. If you run into a wall, figure out how to climb it, go through it, or work around it.", "障礙不必讓你停下。撞到牆，就想辦法爬過去、穿過去或繞過去。", "Michael Jordan"),
    ("I always believed that if you put in the work, the results will come.", "我一直相信，只要付出努力，成果自然會來。", "Michael Jordan"),
    ("Champions keep playing until they get it right.", "冠軍會一直打下去，直到做對為止。", "Billie Jean King"),
    ("You miss 100% of the shots you don’t take.", "你不出手，就錯過了百分之百的機會。", "Wayne Gretzky"),
    ("You can’t put a limit on anything. The more you dream, the farther you get.", "任何事都不能設限；夢想越大，走得越遠。", "Michael Phelps"),
    ("I don’t stop when I’m tired; I stop when I’m done.", "我不在疲倦時停下，而是在完成時停下。", "David Goggins"),
    ("Hard days are the best because that’s when champions are made.", "艱難的日子最寶貴，冠軍在此誕生。", "Gabby Douglas"),
    ("Set your goals high, and don’t stop till you get there.", "把目標訂得高一點，達成前不要停。", "Bo Jackson"),
    ("Gold medals aren’t really made of gold. They’re made of sweat, determination, and guts.", "金牌不是金子造的，而是汗水、決心與膽識鑄成的。", "Dan Gable"),
    ("Age is no barrier. It’s a limitation you put on your mind.", "年齡不是障礙，那只是你的心理限制。", "Jackie Joyner-Kersee"),
    ("Excellence is the gradual result of always striving to do better.", "卓越是持續努力追求更好的漸進結果。", "Pat Riley"),
    ("Do not let what you cannot do interfere with what you can do.", "不要讓你做不到的事，妨礙你能做到的事。", "John Wooden"),
    ("It’s not whether you get knocked down; it’s whether you get up.", "被擊倒沒關係，重點是能否站起來。", "Vince Lombardi"),
    ("I never left the field saying I could have done more to get ready, and that gives me peace of mind.", "我從不覺得準備不足離場，這讓我安心。", "Peyton Manning"),
    ("The difference between the impossible and the possible lies in a man’s determination.", "不可能與可能的差別在於決心。", "Tommy Lasorda"),
    ("Run when you can, walk if you have to, crawl if you must; just never give up.", "能跑就跑，能走就走，不行就爬，但絕不放棄。", "Dean Karnazes"),
    ("If you train hard, you’ll not only be hard, you’ll be hard to beat.", "努力訓練，不只變強，更難被擊敗。", "Herschel Walker"),
    ("Victory is in having done your best. If you’ve done your best, you’ve won.", "勝利在於盡力。若你盡了力，你就贏了。", "Bill Bowerman"),
    ("If you don’t have confidence, you’ll always find a way not to win.", "沒有自信，你總會找到輸的理由。", "Carl Lewis"),
    ("What you lack in talent can be made up with desire, hustle, and giving 110% all the time.", "缺天賦可用渴望、拼勁和 110% 投入補足。", "Don Zimmer"),
    ("The harder the battle, the sweeter the victory.", "戰鬥越艱難，勝利越甜美。", "Les Brown"),
    ("Never let the fear of striking out keep you from playing the game.", "別因害怕出局而不上場。", "Babe Ruth"),
    ("Pain is temporary. Quitting lasts forever.", "痛苦是短暫的；放棄是永遠的。", "Lance Armstrong"),
    ("Do today what others won’t so tomorrow you can do what others can’t.", "今天做別人不願做的事，明天你就能做別人不能做的事。", "Jerry Rice"),
    ("The will to win is important, but the will to prepare is vital.", "求勝重要，準備更關鍵。", "Joe Paterno"),
    ("You just can’t beat the person who never gives up.", "你永遠打不倒一個從不放棄的人。", "Babe Ruth"),
    ("Champions act like champions before they are champions.", "在成為冠軍之前，先以冠軍的方式行事。", "Bill Walsh"),
    ("There may be people that have more talent than you, but there’s no excuse for anyone to work harder than you do.", "有人天賦勝你，但冇人有藉口比你更少努力。", "Derek Jeter"),
    ("I became a good pitcher when I stopped trying to make them miss the ball and started trying to make them hit it.", "當我改變策略讓他們打到球，我成為了更好的投手。", "Sandy Koufax"),
    ("Sports do not build character. They reveal it.", "運動不塑造性格，它揭示性格。", "Heywood Broun"),
    ("Success is where preparation and opportunity meet.", "成功是準備與機會的交會點。", "Bobby Unser"),
    ("Perfection is not attainable, but if we chase perfection we can catch excellence.", "完美不可及，但追求完美能抓住卓越。", "Vince Lombardi"),
    ("I hated every minute of training, but I said, ‘Don’t quit. Suffer now and live the rest of your life as a champion.’", "我討厭訓練，但我告訴自己：別放棄。現在吃苦，餘生以冠軍之名。", "Muhammad Ali"),
    ("The man who has no imagination has no wings.", "沒有想像力就沒有翅膀。", "Muhammad Ali"),
    ("He who is not courageous enough to take risks will accomplish nothing in life.", "不敢冒險，終將一事無成。", "Muhammad Ali"),
    ("I don’t have time to worry about what I’m going to do. I just go out and play.", "我冇時間擔心要做咩；我只係上場。", "LeBron James"),
    ("You have to fight to reach your dream. You have to sacrifice and work hard for it.", "為夢想而戰，付出與努力是必須。", "Lionel Messi"),
    ("Dreams are not what you see in your sleep; dreams are the things which do not let you sleep.", "夢想不是睡夢所見，而是令你夜不能寐的事。", "Cristiano Ronaldo"),
    ("Champions are made from something they have deep inside them—a desire, a dream, a vision.", "冠軍來自內心深處的渴望、夢想與願景。", "Muhammad Ali"),
    ("It always seems impossible until it’s done.", "在完成之前，一切看起來都不可能。", "Nelson Mandela"),
    ("Courage is not the absence of fear, but the triumph over it.", "勇氣不是沒有恐懼，而是戰勝恐懼。", "Nelson Mandela"),
    ("The secret of getting ahead is getting started.", "領先的秘密在於開始行動。", "Mark Twain"),
    ("It’s not the size of the dog in the fight, it’s the size of the fight in the dog.", "決定勝負的不是狗的體型，而是牠心中的戰意。", "Mark Twain"),
    ("Keep your face always toward the sunshine—and shadows will fall behind you.", "永遠面向陽光，陰影自然落在背後。", "Walt Whitman"),
    ("If you can dream it, you can do it.", "如果你能夢想到它，你就能做到它。", "Walt Disney"),
    ("The only limit to our realization of tomorrow is our doubts of today.", "實現明日的唯一限制，是我們今日的懷疑。", "Franklin D. Roosevelt"),
    ("Believe you can and you’re halfway there.", "相信自己能做到，你就已成功一半。", "Theodore Roosevelt"),
    ("Do what you can, with what you have, where you are.", "在你所在，用你所有，做你所能。", "Theodore Roosevelt"),
    ("Start where you are. Use what you have. Do what you can.", "從你所在之處開始，利用你所有，盡你所能。", "Arthur Ashe"),
    ("Act as if what you do makes a difference. It does.", "就當你的行動會帶來改變——因為它確實會。", "William James"),
    ("Opportunities don’t happen. You create them.", "機會不是發生；是你創造。", "Chris Grosser"),
    ("The best way to predict the future is to create it.", "預測未來的最佳方法是親手創造。", "Peter Drucker"),
    ("Success is walking from failure to failure with no loss of enthusiasm.", "成功是不失熱情地在失敗間前行。", "Winston Churchill"),
    ("If you’re going through hell, keep going.", "若你正在經歷地獄，繼續走。", "Winston Churchill"),
    ("Failure is not the opposite of success; it’s part of success.", "失敗不是成功的反面，而是成功的一部分。", "Arianna Huffington"),
    ("Everything you’ve ever wanted is on the other side of fear.", "你渴望的一切，都在恐懼的另一邊。", "George Addair"),
    ("Great things are done by a series of small things brought together.", "偉大的事由一連串小事累積而成。", "Vincent van Gogh"),
    ("What lies behind us and what lies before us are tiny matters compared to what lies within us.", "與我們內在相比，過去與未來皆為小事。", "Ralph Waldo Emerson"),
    ("You are never too old to set another goal or to dream a new dream.", "無論年紀多大，都可再設目標或做新夢。", "C. S. Lewis"),
    ("The future belongs to those who believe in the beauty of their dreams.", "未來屬於相信夢想之美的人。", "Eleanor Roosevelt"),
    ("Make each day your masterpiece.", "讓每一天都成為你的代表作。", "John Wooden"),
    ("It’s never too late to be what you might have been.", "成為你想成為的人，永遠不嫌遲。", "George Eliot"),
    ("Success is the sum of small efforts, repeated day in and day out.", "成功是日復一日小努力的總和。", "Robert Collier"),
    ("Do one thing every day that scares you.", "每天做一件讓你害怕的事。", "Eleanor Roosevelt"),
    ("Work hard in silence; let success make the noise.", "默默努力，讓成功發聲。", "Frank Ocean"),
    ("Don’t wish it were easier; wish you were better.", "別求更容易；求自己更強。", "Jim Rohn"),
    ("Little by little, one travels far.", "一點一點地，人能走得很遠。", "J. R. R. Tolkien"),
    ("Doubt kills more dreams than failure ever will.", "懷疑扼殺的夢想比失敗更多。", "Suzy Kassem"),
    ("Hold the vision, trust the process.", "堅守願景，信任過程。", "Jon Gordon"),
    ("Success usually comes to those who are too busy to be looking for it.", "成功往往屬於忙於行動、無暇找成功的人。", "Henry David Thoreau"),
    ("Perseverance is not a long race; it is many short races one after the other.", "堅持不是一場長跑，而是一場接一場的短跑。", "Walter Elliot"),
    ("Your limitation—it’s only your imagination.", "你的限制，只是想像。", "Tony Robbins"),
    ("Great things never come from comfort zones.", "偉大不會來自舒適圈。", "Roy T. Bennett"),
    ("Sometimes we’re tested not to show our weaknesses, but to discover our strengths.", "考驗不是為顯示弱點，而是為發現力量。", "Les Brown"),
    ("Believe in yourself and all that you are.", "相信自己與你的一切。", "Christian D. Larson"),
    ("The only place where success comes before work is in the dictionary.", "成功先於努力的唯一地方，是字典。", "Vidal Sassoon"),
    ("You don’t have to be great to start, but you have to start to be great.", "開始不必偉大，但要開始才會偉大。", "Zig Ziglar"),
    ("Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless.", "限制只在心中；善用想像，可能性無限。", "Jamie Paolinetti"),
    ("Success isn’t always about greatness. It’s about consistency.", "成功不總是關乎偉大，而是關乎持之以恆。", "Dwayne Johnson"),
    ("Strength doesn’t come from what you can do. It comes from overcoming the things you once thought you couldn’t.", "力量不是來自你能做的事，而是克服你以為做不到的事。", "Rikki Rogers"),
    ("Believe in your infinite potential.", "相信你無限的潛能。", "Stephen R. Covey"),
    ("If you want to lift yourself up, lift up someone else.", "想提升自己，先扶起他人。", "Booker T. Washington"),
    ("Success is the sum of details.", "成功是細節的總和。", "Harvey S. Firestone"),
    ("Genius is 1% inspiration and 99% perspiration.", "天才是 1% 靈感加 99% 汗水。", "Thomas A. Edison"),
    ("I have not failed. I’ve just found 10,000 ways that won’t work.", "我沒有失敗，我只是找到了一萬種行不通的方法。", "Thomas A. Edison"),
    ("Whether you think you can, or you think you can’t—you’re right.", "無論你覺得能或不能——你都對。", "Henry Ford"),
    ("Quality means doing it right when no one is looking.", "品質是無人注視時仍把事做對。", "Henry Ford"),
    ("Stay hungry, stay foolish.", "求知若飢，虛懷若愚。", "Steve Jobs"),
    ("The people who are crazy enough to think they can change the world are the ones who do.", "瘋狂到相信能改變世界的人，往往真的做到了。", "Steve Jobs"),
    ("If opportunity doesn’t knock, build a door.", "若機會不敲門，就造一扇門。", "Milton Berle"), 
    ("Do or do not. There is no try.", "要做就做，沒有嘗試。", "Yoda"),
    ("The journey of a thousand miles begins with a single step.", "千里之行，始於足下。", "Laozi"),
    ("Everything has beauty, but not everyone sees it.", "萬物皆有美，但不是人人都看見。", "Confucius"),
    ("We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "我們反覆做什麼，就成為什麼；卓越不是行為，而是習慣。", "Aristotle"),
    ("Happiness depends upon ourselves.", "幸福取決於我們自己。", "Aristotle"),
    ("The only true wisdom is in knowing you know nothing.", "真正的智慧在於知道自己一無所知。", "Socrates"),
    ("Be the change that you wish to see in the world.", "成為你想在世界上看見的改變。", "Mahatma Gandhi"),
    ("Live as if you were to die tomorrow. Learn as if you were to live forever.", "像明天就會死去般地生活，像永遠活著般地學習。", "Mahatma Gandhi"),
    ("Not all those who wander are lost.", "徘徊之人未必迷失。", "J. R. R. Tolkien"),
    ("It is never too late to give up your prejudices.", "放下偏見永遠不嫌遲。", "Henry David Thoreau"),
    ("The successful warrior is the average man, with laser-like focus.", "成功的戰士其實是普通人，但擁有雷射般的專注。", "Bruce Lee"),
    ("Absorb what is useful, discard what is not, add what is uniquely your own.", "吸收有用，剔除無用，加入屬於你的獨特。", "Bruce Lee"),
    ("The key to immortality is first living a life worth remembering.", "通往不朽的關鍵，是先活出值得被記住的人生。", "Bruce Lee"),
    ("Perseverance, secret of all triumphs.", "堅持，是所有勝利的祕密。", "Victor Hugo"),
    ("Even the darkest night will end and the sun will rise.", "最黑暗的夜也會過去，太陽終會升起。", "Victor Hugo"),
    ("Hope is a waking dream.", "希望是醒著的夢。", "Aristotle"),
    ("Fortune favors the bold.", "幸運偏愛勇者。", "Virgil"),
    ("He who has a why to live can bear almost any how.", "知道為什麼而活的人，幾乎可以承受任何生活方式。", "Friedrich Nietzsche"),
    ("We are what we think.", "我們即是我們所想。", "Buddha"),
    ("No one saves us but ourselves. We ourselves must walk the path.", "除了我們自己，沒有人能拯救我們。我們必須自行走這條路。", "Buddha"),
    ("The only impossible journey is the one you never begin.", "唯一不可能的旅程，是你從未開始的那一段。", "Tony Robbins"),
    ("Success is not final, failure is not fatal: it is the courage to continue that counts.", "成功非終點，失敗非末日；關鍵是繼續的勇氣。", "Winston Churchill"),
    ("If you want to go fast, go alone. If you want to go far, go together.", "想走快，獨自走；想走遠，一起走。", "African Proverb"),
    ("Alone we can do so little; together we can do so much.", "獨自能做很少，攜手能做很多。", "Helen Keller"),
    ("Life is either a daring adventure or nothing at all.", "人生非大膽冒險，便一無所有。", "Helen Keller"),
    ("Keep moving forward.", "不斷向前。", "Walt Disney"),
    ("Strive not to be a success, but rather to be of value.", "別只追求成功，要努力成為有價值的人。", "Albert Einstein"),
    ("Life is like riding a bicycle. To keep your balance you must keep moving.", "人生像騎單車，為了平衡必須前進。", "Albert Einstein"),
    ("In the middle of difficulty lies opportunity.", "困難之中自有機會。", "Albert Einstein"),
    ("I am not a product of my circumstances. I am a product of my decisions.", "我不是環境的產物，而是選擇的產物。", "Stephen R. Covey"),
    ("Begin with the end in mind.", "以終為始。", "Stephen R. Covey"),
    ("The best revenge is massive success.", "最好的報復是巨大的成功。", "Frank Sinatra"),
    ("Difficulties strengthen the mind, as labor does the body.", "艱難鍛鍊心志，如同勞動鍛鍊身體。", "Seneca"),
    ("Luck is what happens when preparation meets opportunity.", "當準備遇上機會，就叫運氣。", "Seneca"),
    ("We suffer more often in imagination than in reality.", "我們常在想像中受苦多於現實。", "Seneca"),
    ("Do not pray for an easy life, pray for the strength to endure a difficult one.", "別祈求容易的人生，祈求承受艱難的力量。", "Bruce Lee"),
    ("Be yourself; everyone else is already taken.", "做你自己，其他人都已有人扮演。", "Oscar Wilde"),
    ("To live is the rarest thing in the world. Most people exist, that is all.", "活著是世上最稀有的事，大多數人只是存在而已。", "Oscar Wilde"),
    ("Success is liking yourself, liking what you do, and liking how you do it.", "成功就是喜歡自己，喜歡你做的事，喜歡你做事的方式。", "Maya Angelou"),
    ("Try not to become a man of success. Rather become a man of value.", "不要努力成為成功的人，要努力成為有價值的人。", "Albert Einstein"),
    ("Success means having the courage, the determination, and the will to become the person you believe you were meant to be.", "成功意味著有勇氣、有決心，並有意志成為你相信自己應該成為的人。", "George Sheehan"),
    ("Fall seven times and stand up eight.", "跌倒七次，第八次要站起來。", "Japanese Proverb"),
    ("Don’t let the fear of losing be greater than the excitement of winning.", "不要讓輸的恐懼大於贏的興奮。", "Robert Kiyosaki"),
    ("Success seems to be connected with action. Successful people keep moving.", "成功似乎與行動有關。成功的人會不斷前進。", "Conrad Hilton"),
    ("Energy and persistence conquer all things.", "精力與堅持能征服一切。", "Benjamin Franklin"),
    ("Do not wait to strike till the iron is hot; but make it hot by striking.", "不要等鐵熱才打，而是靠打使鐵變熱。", "William Butler Yeats"),
    ("What you get by achieving your goals is not as important as what you become by achieving your goals.", "實現目標所得不如實現目標所成就的自己重要。", "Zig Ziglar"),
    ("The way to get started is to quit talking and begin doing.", "開始的方法就是少說話，多行動。", "Walt Disney"),
    ("Don’t be afraid to give up the good to go for the great.", "不要害怕放棄好的去追求更好的。", "John D. Rockefeller"),
    ("Success usually comes to those who are too busy to be looking for it.", "成功通常屬於那些忙得沒時間找成功的人。", "Henry David Thoreau"),
    ("Opportunities multiply as they are seized.", "機會越抓越多。", "Sun Tzu"),
    ("An ounce of practice is worth more than tons of preaching.", "一盎司的實踐勝過噸位的說教。", "Mahatma Gandhi"),
    ("Success is the progressive realization of a worthy goal or ideal.", "成功是逐步實現一個有價值的目標或理想。", "Earl Nightingale"),
    ("The harder you work, the luckier you get.", "你越努力，就越幸運。", "Gary Player"),
    ("Act or accept.", "要麼行動，要麼接受現狀。", "Anonymous Greek Proverb"),
    ("In order to succeed, your desire for success should be greater than your fear of failure.", "為了成功，你對成功的渴望必須大於對失敗的恐懼。", "Bill Cosby"),
    ("Do not be embarrassed by your failures, learn from them and start again.", "不要因失敗而尷尬，從中學習再出發。", "Richard Branson"),
    ("The only way to achieve the impossible is to believe it is possible.", "達成不可能的唯一方法就是相信它可能。", "Charles Kingsleigh (Alice in Wonderland)"),
    ("The best preparation for tomorrow is doing your best today.", "為明天準備最好的方法就是今天做到最好。", "H. Jackson Brown Jr."),
    ("Don’t let yesterday take up too much of today.", "別讓昨天佔據太多今天。", "Will Rogers"),
    ("It does not matter how slowly you go as long as you do not stop.", "只要不停下來，走得多慢都沒關係。", "Confucius"),
    ("Perseverance is failing 19 times and succeeding the 20th.", "毅力就是失敗 19 次，第 20 次成功。", "Julie Andrews"),
    ("Do not go where the path may lead, go instead where there is no path and leave a trail.", "不要循著已有的路走，而是去沒有路的地方，留下自己的足跡。", "Ralph Waldo Emerson"),
    ("Your time is limited, so don’t waste it living someone else’s life.", "你的時間有限，不要浪費在過別人的生活上。", "Steve Jobs"),
    ("Innovation distinguishes between a leader and a follower.", "創新區分領袖與跟隨者。", "Steve Jobs"),
    ("Sometimes life hits you in the head with a brick. Don’t lose faith.", "有時生活會用磚頭砸你頭上，不要失去信心。", "Steve Jobs"),
    ("Good artists copy, great artists steal.", "好的藝術家抄襲，偉大的藝術家偷取。", "Pablo Picasso"),
    ("Action is the foundational key to all success.", "行動是一切成功的基石。", "Pablo Picasso"),
    ("Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", "不要沉湎於過去，不要夢想未來，把心思集中在當下。", "Buddha"),
    ("Three things cannot be long hidden: the sun, the moon, and the truth.", "三件事不能長久隱藏：太陽、月亮與真相。", "Buddha"),
    ("Peace comes from within. Do not seek it without.", "平靜來自內心，不要向外尋找。", "Buddha"),
    ("Turn your wounds into wisdom.", "將傷口化為智慧。", "Oprah Winfrey"),
    ("Doing the best at this moment puts you in the best place for the next moment.", "此刻做到最好，就能在下一刻處於最佳位置。", "Oprah Winfrey"),
    ("Passion is energy. Feel the power that comes from focusing on what excites you.", "熱情是能量，專注於讓你興奮的事會帶來力量。", "Oprah Winfrey"),
    ("The question isn’t who’s going to let me; it’s who’s going to stop me.", "問題不是誰允許我，而是誰能阻止我。", "Ayn Rand"),
    ("Wealth consists not in having great possessions, but in having few wants.", "財富不在於擁有很多，而在於欲望很少。", "Epictetus"),
    ("Man is not worried by real problems so much as by his imagined anxieties about real problems.", "人並非被真正的問題困擾，而是被對問題的想像焦慮困擾。", "Epictetus"),
    ("First say to yourself what you would be; and then do what you have to do.", "先告訴自己你想成為什麼人，然後做該做的事。", "Epictetus"),
    ("Don’t count the days; make the days count.", "不要數著日子過，要讓日子有價值。", "Muhammad Ali"),
    ("I hated every minute of training, but I said, ‘Don’t quit. Suffer now and live the rest of your life as a champion.’", "我討厭每分鐘訓練，但我告訴自己：別放棄。現在忍受痛苦，餘生以冠軍身份生活。", "Muhammad Ali"),
    ("He who is not courageous enough to take risks will accomplish nothing in life.", "沒有勇氣冒險的人，終將一事無成。", "Muhammad Ali"),
    ("Float like a butterfly, sting like a bee.", "像蝴蝶般翩翩起舞，像蜜蜂般狠狠刺擊。", "Muhammad Ali"),
    ("It’s not bragging if you can back it up.", "如果你能做到，就不是吹牛。", "Muhammad Ali"),
    ("The fight is won or lost far away from witnesses—behind the lines, in the gym, and out there on the road, long before I dance under those lights.", "勝負早在沒人見的地方決定——後方、健身房、路上，遠早於我在燈光下跳舞。", "Muhammad Ali"),
    ("You have to expect things of yourself before you can do them.", "你要先對自己有所期待，才能做到事情。", "Michael Jordan"),
    ("Some people want it to happen, some wish it would happen, others make it happen.", "有些人希望它發生，有些人期待它發生，另一些人讓它發生。", "Michael Jordan"),
    ("My attitude is that if you push me towards something that you think is a weakness, then I will turn that perceived weakness into a strength.", "我的態度是，如果你把我推向你認為的弱點，我會把那個弱點轉化為強項。", "Michael Jordan"),
    ("Never say never, because limits, like fears, are often just an illusion.", "永遠不要說不可能，因為限制就像恐懼，往往只是幻覺。", "Michael Jordan"),
    ("I can accept failure, everyone fails at something. But I can’t accept not trying.", "我可以接受失敗，因為每個人都會失敗。但我不能接受不嘗試。", "Michael Jordan"),
    ("If you quit once it becomes a habit. Never quit!", "放棄一次就會成習慣。永不放棄！", "Michael Jordan"),
    ("To be successful you have to be selfish, or else you never achieve. And once you get to your highest level, then you have to be unselfish.", "要成功必須先自私，不然無法達成；到達最高境界後，則要無私。", "Michael Jordan"),
    ("I've never lost a game. I just ran out of time.", "我從未輸過比賽，只是時間不夠。", "Michael Jordan"),
    ("A champion is someone who gets up when he can’t.", "冠軍是那個在無法再起身時仍站起來的人。", "Jack Dempsey"),
    ("The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.", "成功者與他人的差別不是力量或知識，而是意志。", "Vince Lombardi"),
    ("Winning isn’t everything, it’s the only thing.", "勝利不是一切，它是唯一。", "Vince Lombardi"),
    ("Practice does not make perfect. Only perfect practice makes perfect.", "練習不會造就完美，只有完美的練習才能造就完美。", "Vince Lombardi"),
    ("Leaders aren’t born, they are made.", "領袖不是天生，而是後天造就的。", "Vince Lombardi"),
    ("Confidence is contagious. So is lack of confidence.", "自信是會傳染的；缺乏自信亦然。", "Vince Lombardi"),
    ("The price of success is hard work, dedication to the job at hand, and determination that whether we win or lose, we have applied the best of ourselves to the task at hand.", "成功的代價是努力工作、專注眼前，無論輸贏，我們都全力以赴。", "Vince Lombardi"),
    ("It’s not whether you get knocked down, it’s whether you get up.", "不是被擊倒，而是能否再站起來。", "Vince Lombardi"),
    ("Perfection is not attainable, but if we chase perfection we can catch excellence.", "完美不可及，但若追求完美可抓住卓越。", "Vince Lombardi"),
    ("The greatest accomplishment is not in never falling, but in rising again after you fall.", "最偉大的成就不在於從不跌倒，而在於跌倒後能再站起來。", "Vince Lombardi"),
    ("Success is liking yourself, liking what you do, and liking how you do it.", "成功就是喜歡自己、喜歡你做的事、也喜歡你做事的方式。", "Maya Angelou"),
    ("Try not to become a man of success. Rather become a man of value.", "不要努力成為成功的人，要努力成為有價值的人。", "Albert Einstein"),
    ("What you get by achieving your goals is not as important as what you become by achieving your goals.", "實現目標所得到的不如你因此成為怎樣的人重要。", "Zig Ziglar"),
    ("Energy and persistence conquer all things.", "精力與堅持能征服一切。", "Benjamin Franklin"),
    ("Opportunities multiply as they are seized.", "機會因把握而倍增。", "Sun Tzu"),
    ("The best way to predict the future is to create it.", "預測未來的最佳方式，就是親手創造。", "Peter Drucker"),
    ("Courage is grace under pressure.", "勇氣是在壓力下仍保持風度。", "Ernest Hemingway"),
    ("The only limit to our realization of tomorrow is our doubts of today.", "實現明日的唯一限制，是我們今日的懷疑。", "Franklin D. Roosevelt"),
    ("Believe you can and you're halfway there.", "相信自己能做到，你就已經成功一半。", "Theodore Roosevelt"),
    ("Act as if what you do makes a difference. It does.", "就當你的行動會帶來改變——因為它確實會。", "William James"),
    ("Do what you can, with what you have, where you are.", "在你所在之處，用你所有，做你所能。", "Theodore Roosevelt"),
    ("Start where you are. Use what you have. Do what you can.", "從你所在之處開始，利用你手上所擁有，盡你所能去做。", "Arthur Ashe"),
    ("Success is walking from failure to failure with no loss of enthusiasm.", "成功就是不失熱情地從一次失敗走向另一次失敗。", "Winston Churchill"),
    ("If you're going through hell, keep going.", "如果你正在經歷地獄，繼續走下去。", "Winston Churchill"),
    ("Do not wait to strike till the iron is hot; but make it hot by striking.", "不要等鐵熱才打，而是靠打使鐵變熱。", "William Butler Yeats"),
    ("Everything you've ever wanted is on the other side of fear.", "你曾渴望的一切，都在恐懼的另一邊。", "George Addair"),
    ("It always seems impossible until it's done.", "在完成之前，一切看起來都不可能。", "Nelson Mandela"),
    ("Courage is not the absence of fear, but the triumph over it.", "勇氣不是沒有恐懼，而是戰勝恐懼。", "Nelson Mandela"),
    ("Make each day your masterpiece.", "讓每一天都成為你的代表作。", "John Wooden"),
    ("Do not let what you cannot do interfere with what you can do.", "不要讓你做不到的事，妨礙你能做到的事。", "John Wooden"),
    ("The only place where success comes before work is in the dictionary.", "唯一成功先於努力的地方，是字典裡。", "Vidal Sassoon"),
    ("You don't have to be great to start, but you have to start to be great.", "開始不必偉大，但你必須開始，才能變得偉大。", "Zig Ziglar"),
    ("Dream big and dare to fail.", "做大夢，敢於失敗。", "Norman Vaughan"),
    ("Quality is not an act, it is a habit.", "品質不是一個動作，而是一種習慣。", "Aristotle"),
    ("Well done is better than well said.", "做得好勝過說得好。", "Benjamin Franklin"),
    ("Change your thoughts and you change your world.", "改變你的想法，你就改變了你的世界。", "Norman Vincent Peale"),
    ("It does not matter how slowly you go as long as you do not stop.", "只要不停下來，走得多慢都沒關係。", "Confucius"),
    ("Our greatest glory is not in never falling, but in rising every time we fall.", "我們最偉大的榮耀不在於從不跌倒，而是每次跌倒後都能再站起來。", "Confucius"),
    ("The man who moves a mountain begins by carrying away small stones.", "搬山之人，始於移石。", "Confucius"),
    ("He who has a why to live can bear almost any how.", "知道為什麼而活的人，幾乎可以承受任何怎樣活。", "Friedrich Nietzsche"),
    ("What we think, we become.", "我們所思，即我們所成。", "Buddha"),
    ("No one saves us but ourselves. We ourselves must walk the path.", "除了我們自己，沒有人能拯救我們。我們自己必須走這條道路。", "Buddha"),
    ("In the middle of difficulty lies opportunity.", "困難之中自有機會。", "Albert Einstein"),
    ("I have not failed. I've just found 10,000 ways that won't work.", "我沒有失敗，我只是找到了一萬種行不通的方法。", "Thomas A. Edison"),
    ("Genius is one percent inspiration and ninety-nine percent perspiration.", "天才是 1% 靈感與 99% 汗水。", "Thomas A. Edison"),
    ("Whether you think you can, or you think you can't—you're right.", "無論你覺得能或不能——你都對。", "Henry Ford"),
    ("If you can dream it, you can do it.", "如果你能夢想到它，你就能做到它。", "Walt Disney"),
    ("Keep moving forward.", "不斷向前。", "Walt Disney"),
    ("The future belongs to those who believe in the beauty of their dreams.", "未來屬於相信夢想之美的人。", "Eleanor Roosevelt"),
    ("Do one thing every day that scares you.", "每天做一件讓你害怕的事。", "Eleanor Roosevelt"),
    ("Be yourself; everyone else is already taken.", "做你自己，其他人都已有人扮演。", "Oscar Wilde"),
    ("What would life be if we had no courage to attempt anything?", "如果沒有勇氣嘗試，人生會是怎樣？", "Vincent van Gogh"),
    ("Great things are done by a series of small things brought together.", "偉大的事由一連串小事累積而成。", "Vincent van Gogh"),
    ("You miss 100% of the shots you don't take.", "你不出手，就錯過了百分之百的機會。", "Wayne Gretzky"),
    ("I've failed over and over and over again in my life and that is why I succeed.", "我一生中一次又一次失敗，因此我才成功。", "Michael Jordan"),
    ("Talent wins games, but teamwork and intelligence win championships.", "天賦能贏比賽，但團隊合作與智慧才能贏得冠軍。", "Michael Jordan"),
    ("I can accept failure, everyone fails at something. But I can't accept not trying.", "我可以接受失敗，但不能接受不嘗試。", "Michael Jordan"),
    ("The more difficult the victory, the greater the happiness in winning.", "勝利越艱難，贏得時的喜悅就越大。", "Pelé"),
    ("Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and most of all, love of what you are doing.", "成功不是偶然，它是努力、堅持、學習、犧牲，更重要的是對所做事情的熱愛。", "Pelé"),
    ("You have to fight to reach your dream. You have to sacrifice and work hard for it.", "你必須奮鬥才能實現夢想，你必須為此付出犧牲與努力。", "Lionel Messi"),
    ("Dreams are not what you see in your sleep; dreams are the things which do not let you sleep.", "夢想不是你在睡夢中所見，而是那些讓你無法入眠的事物。", "Cristiano Ronaldo"),
    ("I don't run to see who is the fastest. I run to see who has the most guts.", "我跑步不是為了看誰最快，而是看誰最有膽識。", "Steve Prefontaine"),
    ("You can't put a limit on anything. The more you dream, the farther you get.", "任何事都不能設限；夢想越大，你走得越遠。", "Michael Phelps"),
    ("Hard days are the best because that's when champions are made.", "艱難的日子最寶貴，因為冠軍就是在這時誕生。", "Gabby Douglas"),
    ("Champions keep playing until they get it right.", "冠軍會一直打下去，直到做對為止。", "Billie Jean King"),
    ("A champion is defined not by their wins, but by how they can recover when they fall.", "冠軍的定義不在於勝利多少，而在於跌倒後如何站起來。", "Serena Williams"),
    ("There may be people that have more talent than you, but there's no excuse for anyone to work harder than you do.", "有人天賦勝你，但冇人有藉口比你更少努力。", "Derek Jeter"),
    ("Champions act like champions before they are champions.", "在成為冠軍之前，先以冠軍的方式行事。", "Bill Walsh"),
    ("Excellence is the gradual result of always striving to do better.", "卓越是持續努力追求更好的一個漸進結果。", "Pat Riley"),
    ("It’s not whether you get knocked down; it’s whether you get up.", "被擊倒沒關係，重點是你能否站起來。", "Vince Lombardi"),
    ("Winning isn't everything, but wanting to win is.", "勝利不是一切，但想贏才是一切。", "Vince Lombardi"),
    ("Perfection is not attainable, but if we chase perfection we can catch excellence.", "完美不可及，但若追求完美，我們可抓住卓越。", "Vince Lombardi"),
    ("It's hard to beat a person who never gives up.", "很難擊敗一個永不放棄的人。", "Babe Ruth"),
    ("Pain is temporary. Quitting lasts forever.", "痛苦是短暫的，放棄卻是永遠的。", "Lance Armstrong"),
    ("Do today what others won't so tomorrow you can do what others can't.", "今天做別人不願做的事，明天你就能做別人不能做的事。", "Jerry Rice"),
    ("Gold medals aren't really made of gold. They're made of sweat, determination, and guts.", "金牌不是金子造的，而是汗水、決心與膽識鑄成的。", "Dan Gable"),
    ("Set your goals high, and don't stop till you get there.", "把目標訂得高一點，直到達成前都不要停。", "Bo Jackson"),
    ("A winner is a dreamer who never gives up.", "贏家是不會放棄的夢想家。", "Nelson Mandela"),
    ("It always seems impossible until it’s done.", "在完成之前，一切看起來都不可能。", "Nelson Mandela"),
    ("Success is not final, failure is not fatal: it is the courage to continue that counts.", "成功非終點，失敗非末日；關鍵是繼續的勇氣。", "Winston Churchill"),
    ("Success is the sum of small efforts, repeated day in and day out.", "成功是日復一日重複的小努力之總和。", "Robert Collier"),
    ("Little by little, one travels far.", "一點一點地，人就能走得很遠。", "J. R. R. Tolkien"),
    ("Stay hungry, stay foolish.", "求知若飢，虛懷若愚。", "Steve Jobs"),
    ("The people who are crazy enough to think they can change the world are the ones who do.", "瘋狂到相信自己能改變世界的人，往往真的做到了。", "Steve Jobs"),
    ("Your time is limited, so don't waste it living someone else's life.", "你的時間有限，不要浪費在過別人的生活上。", "Steve Jobs"),
    ("Innovation distinguishes between a leader and a follower.", "創新區分領袖與跟隨者。", "Steve Jobs"),
    ("If opportunity doesn't knock, build a door.", "若機會不敲門，就造一扇門。", "Milton Berle"),
    ("Fortune favors the bold.", "幸運偏愛勇者。", "Virgil"),
    ("He who is brave is free.", "勇者自由。", "Seneca"),
    ("Luck is what happens when preparation meets opportunity.", "當準備遇上機會，就叫運氣。", "Seneca"),
    ("Difficulties strengthen the mind, as labor does the body.", "艱難鍛鍊心志，如同勞動鍛鍊身體。", "Seneca"),
    ("You must be the change you wish to see in the world.", "成為你想在世界上看見的改變。", "Mahatma Gandhi"),
    ("Live as if you were to die tomorrow. Learn as if you were to live forever.", "像明天就會死去般地生活，像永遠活著般地學習。", "Mahatma Gandhi"),
    ("Not all those who wander are lost.", "徘徊之人未必迷失。", "J. R. R. Tolkien"),
    ("What you do speaks so loudly that I cannot hear what you say.", "你的行動響亮到我聽不見你在說什麼。", "Ralph Waldo Emerson"),
    ("What lies behind us and what lies before us are tiny matters compared to what lies within us.", "與我們內在相比，過去與未來皆為小事。", "Ralph Waldo Emerson"),
    ("Vision without execution is hallucination.", "沒有執行力的願景只是幻覺。", "Thomas A. Edison"),
    ("If you want to lift yourself up, lift up someone else.", "如果你想提升自己，先幫助別人。", "Booker T. Washington"),
    ("I am not a product of my circumstances. I am a product of my decisions.", "我不是環境的產物，而是選擇的產物。", "Stephen R. Covey"),
    ("Begin with the end in mind.", "以終為始。", "Stephen R. Covey"),
    ("The only impossible journey is the one you never begin.", "唯一不可能的旅程，是你從未開始的那一段。", "Tony Robbins"),
    ("It’s never too late to be what you might have been.", "成為你想成為的人，永遠不嫌遲。", "George Eliot"),
    ("We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "我們反覆做什麼，就成為什麼；卓越不是行為，而是習慣。", "Aristotle"),
    ("Happiness depends upon ourselves.", "幸福取決於我們自己。", "Aristotle"),
]

# 每人 30 秒冷卻
COOLDOWN = app_commands.checks.cooldown(1, 30.0, key=lambda i: i.user.id)

class Cheers(commands.Cog):
    def __init__(self, bot: commands.Bot):
        self.bot = bot

    @app_commands.command(name="cheers", description="隨機派一句名人鼓勵語錄（中英對照，Embed）")
    @app_commands.guilds(discord.Object(id=config.GUILD_ID))
    @app_commands.describe(to="可選：@某人，送上鼓勵")
    @COOLDOWN
    async def cheers_cmd(self, inter: discord.Interaction, to: discord.Member | None = None):
        eng, zh, author = random.choice(CHEERS_QUOTES)

        # mention 放在最前段
        if to:
            desc = f"🎉 給 {to.mention} 的打氣！\n\n**{author} 講過：**"
        else:
            desc = f"🎉 打氣時間！\n\n**{author} 講過：**"

        embed = Embed(description=desc, color=0x57F287)
        embed.add_field(name="English", value=f"💬 {eng}", inline=False)
        embed.add_field(name="中文", value=f"➡️ {zh}", inline=False)

        embed.set_footer(text="Con9sole-Bartender Cheers")
        embed.timestamp = discord.utils.utcnow()

        await inter.response.send_message(embed=embed)

async def setup(bot: commands.Bot):
    await bot.add_cog(Cheers(bot))
